<?php

namespace Vivacom\CmsBundle\Model;

use Vivacom\CmsBundle\Model\om\BasePageQuery;


/**
 * Skeleton subclass for performing query and update operations on the 'page' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Wed May 18 17:46:46 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.media.Dati.internet.sf2.src.Vivacom.CmsBundle.Model
 */
class PageQuery extends BasePageQuery {

} // PageQuery
