imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
    
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   sf2_test
        user:     sf2_test
        password: ~
        charset:  UTF8
