imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true


propel:
    dbal:
        driver:               mysql
        user:                 sf2
        password:             ""
        dsn:                  mysql:host=localhost;dbname=sf2
        options:              {}
        attributes:           {}
#        default_connection:       default
#        connections:
#           default:
#               driver:               mysql
#               user:                 root
#               password:             null
#               dsn:                  mysql:host=localhost;dbname=test
#               options:              {}
#               attributes:           {}