imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@CmsBundle/Resources/config/services.yml" }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
    translator:      { fallback: en }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    assets:
        compass_screen:
            inputs: [ "@CmsBundle/Resources/compass/sass/screen.sass" ]
        screen_css:
            inputs: "@compass_screen"
            filters: compass
    filters:
        cssrewrite: ~
        scss:       ~
        sass:       ~
        yui_js:
          jar:      %kernel.root_dir%/java/yuicompressor-2.4.6.jar
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
avalanche_imagine:
    driver: gd
    filters:
        cypress_assets_gallery_asset:
            type:    thumbnail
            options: { size: [128, 128], mode: inset }    

#fos_user:
#    db_driver: orm
#    firewall_name: main
#    class:
#        model:
#            user: Vivacom\CmsBundle\Entity\User


#propel:
#    path:       "%kernel.root_dir%/../vendor/propel"
#    phing_path: "%kernel.root_dir%/../vendor/phing"
#    charset:   "UTF8"
#    logging:   %kernel.debug%
#    build_properties:
#        xxxxx.xxxxx: xxxxxx
#        xxxxx.xxxxx: xxxxxx

assets_gallery:
    base_path: assets_gallery
