## YAML Template.

parameters:
  assetic.compass.class: Cypress\CompassGemBundle\Assetic\Filter\CompassFilter
  assetic.compass.compass_path: "/var/lib/gems/1.8/bin/compass"
  assetic.compass.images_dir: "%kernel.root_dir%/../src/Vivacom/CmsBundle/Resources/public/images"
  assetic.compass.http_path: /bundles/cms
  utilities.class: Vivacom\CmsBundle\Util\Util
  page.class: Vivacom\CmsBundle\Entity\Page
  
  

services:
  compass:
    class:     %assetic.compass.class%
    arguments: [%assetic.compass.compass_path%]
    calls:
      - [ "setImagesDir", [ %assetic.compass.images_dir% ] ]
      - [ "setHttpPath", [ %assetic.compass.http_path% ] ]
    tags:
      - { name: assetic.filter, alias: compass }
      
      
  utilities_page:
    class: Vivacom\CmsBundle\Entity\Page
    arguments: [%utilities.class%]
    
  utilities_meta:
    class: Vivacom\CmsBundle\Entity\Meta
    arguments: [%utilities.class%]
    
  vivacom.cms.admin.page:
    class: Vivacom\CmsBundle\Admin\PageAdmin
    arguments: [ null, Vivacom\CmsBundle\Entity\Page, "CmsBundle:PageAdmin" ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Pages, label: Page }
      
  vivacom.cms.admin.meta:
    class: Vivacom\CmsBundle\Admin\MetaAdmin
    arguments: [ null, Vivacom\CmsBundle\Entity\Meta, "CmsBundle:MetaAdmin" ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Pages, label: Meta }