#homepage:
#    pattern:  /
#    defaults: { _controller: CypressAssetsGalleryBundle:Default:index }

# LIST
cypress_gallery_list:
    pattern: /{folder_id}
    defaults: { _controller: assets_gallery.controller:listAction, folder_id: ~ }


# ASSETS 
cypress_gallery_asset_manage:
    pattern: /asset/manage/{id}
    defaults: { _controller: assets_gallery.controller:manageAssetAction, id: ~ }
    
cypress_gallery_asset_delete:
    pattern: /asset/{id}/delete
    defaults: { _controller: assets_gallery.controller:deleteAssetAction }
    
cypress_gallery_asset_add_in_folder:
    pattern: /asset/add-in-folder/{id}
    defaults: { _controller: assets_gallery.controller:addAssetInFolder }
    
    
# FOLDERS
cypress_gallery_folder_manage:
    pattern: /folder/manage/{id}
    defaults: { _controller: assets_gallery.controller:manageFolderAction, id: ~ }
    
cypress_gallery_folder_delete:
    pattern: /folder/{id}/delete
    defaults: { _controller: assets_gallery.controller:deleteFolderAction }
    
cypress_gallery_folder_add_in_folder:
    pattern: /folder/add-in-folder/{id}
    defaults: { _controller: assets_gallery.controller:addFolderInFolder }
    
    
# ACTIONS
cypress_gallery_sort_folders:
    pattern: /folder/sort
    defaults: { _controller: assets_gallery.controller:sortFolderAction }