#homepage:
#    pattern:  /
#    defaults: { _controller: CypressAssetsGalleryBundle:Default:index }


cypress_gallery:
    pattern: /gallery
    defaults: { _controller: assets_gallery.controller:listAction }
    
cypress_gallery_add:
    pattern: /gallery/add
    defaults: { _controller: assets_gallery.controller:addAction }