#homepage:
#    pattern:  /
#    defaults: { _controller: CypressAssetsGalleryBundle:Default:index }

#LIST
cypress_gallery_list:
    pattern: /gallery/{folder_id}
    defaults: { _controller: assets_gallery.controller:listAction, folder_id: ~ }


#ASSETS 
cypress_gallery_asset_manage:
    pattern: /gallery/asset/manage/{id}
    defaults: { _controller: assets_gallery.controller:manageAssetAction, id: ~ }
    
cypress_gallery_asset_delete:
    pattern: /gallery/asset/{id}/delete
    defaults: { _controller: assets_gallery.controller:deleteAssetAction }
    
    
#FOLDERS
cypress_gallery_folder_manage:
    pattern: /gallery/folder/manage/{id}
    defaults: { _controller: assets_gallery.controller:manageFolderAction, id: ~ }
    
cypress_gallery_folder_delete:
    pattern: /gallery/folder/{id}/delete
    defaults: { _controller: assets_gallery.controller:deleteFolderAction }